version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: strapi-framework-7