version: 2.1
orbs:
  terraform: circleci/terraform@3.2.1
workflows:
    example-workflow:
      jobs:
        - terraform/validate:
            checkout: true
            path: ./terraform
            context: terraform
        - terraform/plan:
            checkout: true
            context: terraform
            persist-workspace: true
            path: ./terraform 
            out: tfplan 
            requires:
              - terraform/validate
        - terraform/apply:
            attach-workspace: true
            path: ./terraform
            plan: tfplan
            context: terraform
            requires:
              - terraform/plan
