version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  terraform: circleci/terraform@3.2.1

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: strapi-framework-7
  deploy-infra:
      jobs:
        - terraform/validate:
            path: ./terraform 
            context: aws
        - terraform/plan:
            attach-workspace: false 
            out: tfplan 
            path: ./terraform
            context: aws