version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  terraform-v2: ovotech/terraform-v2@2.5.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - terraform-v2/validate:
          path: ./terraform 

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: strapi-framework-7
  deploy-infra:
      jobs:
        - example-job
        - terraform-v2/plan:
            path: ./terraform
            context: aws