version: 2.1
orbs:
  terraform: circleci/terraform@3.2.1
workflows:
    example-workflow:
      jobs:
        - terraform/init:
            path: ./terraform
        - terraform/plan:
            path: ./terraform 
            out: tfplan 
        - terraform/apply:
            path: ./terraform
            plan: tfplan
