version: 2.1
orbs:
  terraform: circleci/terraform@3.2.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - terraform/validate:
          path: .
      - terraform/plan:
          path: .
          out: tfplan
      - terraform/apply:
          path: .
          plan: tfplan
    working_directory: ./terraform
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle:
          context: terraform


    
# workflows:
#   example-workflow:
#     jobs:
#       - example-job
      
