version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  terraform: circleci/terraform@3.2.1
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  single-job-lifecycle:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      # - aws-cli/install:
      #     disable-aws-pager: true
      # - aws-cli/setup
      - checkout
      - run:
          name: terraform init & plan
          command: |
            export AWS_CONFIG_FILE=~/.aws/config
            export AWS_SHARED_CREDENTIALS_FILE=~/.aws/credentials
            terraform -chdir=./terraform init -input=false
            terraform -chdir=./terraform plan -out tfapply

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: strapi-framework-7
      - single-job-lifecycle:
          context: aws
      