version: 2.1
orbs:
  terraform: circleci/terraform@3.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: ./terraform
      - terraform/plan:
          path: ./terraform
          out: tfplan
          input: false
      - terraform/apply:
          path: ./terraform
          plan: tfplan
          input: false
