version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  terraform: circleci/terraform@3.2.1
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  single-job-lifecycle:
    docker:
      - image: cimg/base:stable
    steps:
      - aws-cli/install:
          disable-aws-pager: true
      - aws-cli/setup
      - checkout
      - run:
          name: Check Scripts
          command: |
            cat ~/.aws/config
      - terraform/install:
          arch: amd64 
          os: linux 
      - terraform/init:
          path: ./terraform
      - terraform/validate:
          path: ./terraform
      - terraform/plan:
          path: ./terraform

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: strapi-framework-7
      - single-job-lifecycle:
          context: aws
      