apiVersion: v1
kind: Service
metadata:
  name: strapi-framework-seven-service
  namespace: framwork-demo-dev
spec:
  type: LoadBalancer
  ports:
  - port: 1337
    targetPort: 1337
    protocol: TCP
  selector:
    app: strapi-framework-seven
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-framework-seven-deployment
  namespace: framwork-demo-dev
  labels:
    app: strapi-framework-seven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi-framework-seven
  template:
    metadata:
      labels:
        app: strapi-framework-seven
    spec:
      containers:
      - name: strapi-framework-seven-container
        image: 010854002138.dkr.ecr.ap-southeast-2.amazonaws.com/strapi-framework-7
        imagePullPolicy: Always
        env:
        - name: DATABASE_CLIENT
          value: "postgres"
        - name: DATABASE_HOST
          value: "postgres-multi-db-service"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "strapi_framwork_seven"
        - name: DATABASE_USERNAME
          value: "strapi"
        - name: DATABASE_PASSWORD
          value: "Strapi#1234"
        - name: JWT_SECRET
          value: "jp5IeziKPTjCwADgQse6YA=="
        - name: ADMIN_JWT_SECRET
          value: "VUF+gmtj6WgcITHrW6UC1g=="
        - name: API_TOKEN_SALT
          value: "gsu1G1OsC4KA6Sc9Evos1w=="
        - name: TRANSFER_TOKEN_SALT
          value: "hZNpPHdxT0v74WQRApoTtQ=="
        - name: APP_KEYS
          value: "h1WnvaUfTz19ZRDL7PceNg==,HlI72JUXbUxAu3EF6YAjgQ==,ZNgIASuWF9lZ0k5cmvmDLw==,416pIflMSnXcTLCNYgXwSw=="
        - name: NODE_ENV
          value: "16"
        - name: STRAPI_PORT
          value: "1337"
        ports:
          - name: web
            containerPort: 1337
      imagePullSecrets:
          - name: regcred