apiVersion: v1
kind: Service
metadata:
  name: framework-seven-service
  namespace: framwork-demo-dev
spec:
  type: LoadBalancer
  ports:
  - port: 1337
    targetPort: 1337
    protocol: TCP
  selector:
    app: framework-seven
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: framework-seven-deployment
  namespace: framwork-demo-dev
  labels:
    app: framework-seven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: framework-seven
  template:
    metadata:
      labels:
        app: framework-seven
    spec:
      containers:
      - name: framework-seven-container
        image: 010854002138.dkr.ecr.ap-southeast-2.amazonaws.com/strapi-framework-7
        imagePullPolicy: Always
        env:
        - name: DATABASE_CLIENT
          value: "postgres"
        - name: DATABASE_HOST
          value: "postgres-multi-db-service"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "strapi-framwork-seven"
        - name: DATABASE_USERNAME
          value: "strapi"
        - name: DATABASE_PASSWORD
          value: "Strapi#1234"
        - name: JWT_SECRET
          value: "3AhqUEwurNtw9U3tGMv/Zg=="
        - name: ADMIN_JWT_SECRET
          value: "postgres"
        - name: APP_KEYS
          value: "toBeModified1,toBeModified2"
        - name: NODE_ENV
          value: "16"
        - name: STRAPI_PORT
          value: "1337"
        ports:
          - name: web
            containerPort: 1337
      imagePullSecrets:
          - name: regcred